[package]
name = "mini-backend-database"
version = "0.1.0"
edition = "2024"

[dependencies]
sqlx.workspace = true
chrono.workspace = true
uuid.workspace = true
serde_json.workspace = true
serde.workspace = true
