name: Rust CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install Rust components
        run: |
          rustup component add clippy
          rustup component add rustfmt

      - name: Lint the project
        run: cargo clippy --workspace --all-targets -- -D warnings

      - name: Format the project
        run: cargo fmt --all -- --check

      - name: Test the workspace
        run: cargo test --workspace

      - name: Test the main binary
        run: cargo test